# Base configuration values
backend:
  replicas: 1
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"

frontend:
  replicas: 1
  resources:
    limits:
      cpu: "300m"
      memory: "256Mi"
    requests:
      cpu: "100m"
      memory: "128Mi"

mongodb:
  storage: "10Gi"
  resources:
    limits:
      cpu: "500m"
      memory: "1Gi"