apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: backend-vsvc
spec:
  hosts:
  - backend-svc
  http:
  - route:
    - destination:
        host: backend-svc
        subset: v1
      weight: 90
    - destination:
        host: backend-svc
        subset: v2
      weight: 10
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: backend-dr
spec:
  host: backend-svc
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2